name: Publish Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.402
      - name: Install dependencies
        run: dotnet restore Source/
      - name: Build
        run: dotnet build Source/ --configuration Release --no-restore
      - name: Publish ErosionFinder
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
            PROJECT_FILE_PATH: Source/ErosionFinder/ErosionFinder.csproj
            PACKAGE_NAME: ErosionFinder
            NUGET_KEY: ${{secrets.NUGET_API_KEY}}
            VERSION_REGEX: <version>(.*)<\/version> 